/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alobd
 */
public class Trabalho_menu extends javax.swing.JFrame {

    /**
     * Creates new form Trabalho_menu
     */
    public Trabalho_menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_pratos = new javax.swing.JPanel();
        jrb_risotoPequi = new javax.swing.JRadioButton();
        jrb_risotoAlho = new javax.swing.JRadioButton();
        jrb_macarrao = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jp_pequi = new javax.swing.JLabel();
        jp_acompanhamento = new javax.swing.JPanel();
        jcb_salada = new javax.swing.JCheckBox();
        jcb_legumesGrelhados = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jcb_pimenta = new javax.swing.JCheckBox();
        jcb_molho = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btn_calcular = new javax.swing.JButton();
        btn_novoPedido = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtf_total = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtf_acompanhamento = new javax.swing.JTextField();
        jtf_prato = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jtf_sobremesa = new javax.swing.JTextField();
        jp_sobremesas = new javax.swing.JPanel();
        jrb_mousse = new javax.swing.JRadioButton();
        jrb_tortaOreo = new javax.swing.JRadioButton();
        jrb_petitGateau = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jp_bebidas = new javax.swing.JPanel();
        jrb_agua = new javax.swing.JRadioButton();
        jrb_refrigerante = new javax.swing.JRadioButton();
        jrb_suco = new javax.swing.JRadioButton();
        jrb_destilado = new javax.swing.JRadioButton();
        jrb_vinho = new javax.swing.JRadioButton();
        jrb_cerveja = new javax.swing.JRadioButton();
        jp_cortesia = new javax.swing.JLabel();
        jp_vinho = new javax.swing.JLabel();
        jp_fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jp_pratos.setBackground(new java.awt.Color(255, 255, 255));
        jp_pratos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pratos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gabriola", 1, 18))); // NOI18N

        jrb_risotoPequi.setBackground(new java.awt.Color(255, 255, 255));
        jrb_risotoPequi.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_risotoPequi.setText("Risoto de Frango com Pequi");
        jrb_risotoPequi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_risotoPequiActionPerformed(evt);
            }
        });

        jrb_risotoAlho.setBackground(new java.awt.Color(255, 255, 255));
        jrb_risotoAlho.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_risotoAlho.setText("Risoto de Alho Poró");
        jrb_risotoAlho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_risotoAlhoActionPerformed(evt);
            }
        });

        jrb_macarrao.setBackground(new java.awt.Color(255, 255, 255));
        jrb_macarrao.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_macarrao.setText("Macarrão Caseiro");
        jrb_macarrao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_macarraoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel1.setText("R$ 35,00");

        jLabel3.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel3.setText("R$ 25,00");

        jLabel4.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel4.setText("R$ 20,00");

        jp_pequi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/risotoPequi.png"))); // NOI18N
        jp_pequi.setText("jLabel2");

        javax.swing.GroupLayout jp_pratosLayout = new javax.swing.GroupLayout(jp_pratos);
        jp_pratos.setLayout(jp_pratosLayout);
        jp_pratosLayout.setHorizontalGroup(
            jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pratosLayout.createSequentialGroup()
                .addGroup(jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_risotoAlho)
                    .addComponent(jrb_risotoPequi))
                .addContainerGap(59, Short.MAX_VALUE))
            .addGroup(jp_pratosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jp_pratosLayout.createSequentialGroup()
                .addGroup(jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_macarrao)
                    .addGroup(jp_pratosLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jp_pequi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jp_pratosLayout.setVerticalGroup(
            jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_pratosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_risotoPequi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_pratosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_pratosLayout.createSequentialGroup()
                        .addComponent(jrb_risotoAlho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(jrb_macarrao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4))
                    .addComponent(jp_pequi))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jp_pratos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, 210));

        jp_acompanhamento.setBackground(new java.awt.Color(255, 255, 255));
        jp_acompanhamento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acompanhamentos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gabriola", 1, 18))); // NOI18N
        jp_acompanhamento.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jcb_salada.setBackground(new java.awt.Color(255, 255, 255));
        jcb_salada.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jcb_salada.setText("Saladas ");

        jcb_legumesGrelhados.setBackground(new java.awt.Color(255, 255, 255));
        jcb_legumesGrelhados.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jcb_legumesGrelhados.setText("Legumes Grelhados");

        jLabel5.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel5.setText("R$ 5,00");

        jLabel6.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel6.setText("R$ 8,00");

        jLabel7.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel7.setText("R$ 12,00");

        jcb_pimenta.setBackground(new java.awt.Color(255, 255, 255));
        jcb_pimenta.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jcb_pimenta.setText("Geleia de Pimenta");

        jcb_molho.setBackground(new java.awt.Color(255, 255, 255));
        jcb_molho.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jcb_molho.setText("Molho da Casa");

        jLabel2.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel2.setText("R$ 10,00");

        javax.swing.GroupLayout jp_acompanhamentoLayout = new javax.swing.GroupLayout(jp_acompanhamento);
        jp_acompanhamento.setLayout(jp_acompanhamentoLayout);
        jp_acompanhamentoLayout.setHorizontalGroup(
            jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_acompanhamentoLayout.createSequentialGroup()
                .addGroup(jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jp_acompanhamentoLayout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jcb_salada, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_acompanhamentoLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jp_acompanhamentoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_pimenta, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_legumesGrelhados, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_molho, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jp_acompanhamentoLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(438, 438, 438))
        );
        jp_acompanhamentoLayout.setVerticalGroup(
            jp_acompanhamentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_acompanhamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcb_pimenta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_salada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcb_legumesGrelhados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addComponent(jcb_molho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(1272, 1272, 1272))
        );

        getContentPane().add(jp_acompanhamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 200, 240));

        btn_calcular.setBackground(new java.awt.Color(153, 153, 153));
        btn_calcular.setFont(new java.awt.Font("Gadugi", 1, 18)); // NOI18N
        btn_calcular.setText("Calcular pedido");
        btn_calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(btn_calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, 140, -1));

        btn_novoPedido.setBackground(new java.awt.Color(153, 153, 153));
        btn_novoPedido.setFont(new java.awt.Font("Gadugi", 1, 12)); // NOI18N
        btn_novoPedido.setText("Realizar novo pedido");
        btn_novoPedido.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_novoPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoPedidoActionPerformed(evt);
            }
        });
        getContentPane().add(btn_novoPedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(503, 593, 140, 30));

        jLabel12.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        jLabel12.setText("   Total:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 520, 50, -1));
        getContentPane().add(jtf_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 510, 80, -1));

        jLabel13.setFont(new java.awt.Font("Gabriola", 3, 24)); // NOI18N
        jLabel13.setText(" Buon Appetito!");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, 134, 50));

        jLabel14.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        jLabel14.setText("Acompanhamento:");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        jLabel15.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        jLabel15.setText("             Prato:  ");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 80, -1));
        getContentPane().add(jtf_acompanhamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 80, -1));
        getContentPane().add(jtf_prato, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 80, -1));

        jLabel16.setFont(new java.awt.Font("Gadugi", 1, 10)); // NOI18N
        jLabel16.setText("      Sobremesa:");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 90, -1));
        getContentPane().add(jtf_sobremesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 80, -1));

        jp_sobremesas.setBackground(new java.awt.Color(255, 255, 255));
        jp_sobremesas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sobremesas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gabriola", 1, 18))); // NOI18N

        jrb_mousse.setBackground(new java.awt.Color(255, 255, 255));
        jrb_mousse.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_mousse.setText("Mousse de Chocolate");
        jrb_mousse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_mousseActionPerformed(evt);
            }
        });

        jrb_tortaOreo.setBackground(new java.awt.Color(255, 255, 255));
        jrb_tortaOreo.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_tortaOreo.setText("Torta de Oreo");
        jrb_tortaOreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_tortaOreoActionPerformed(evt);
            }
        });

        jrb_petitGateau.setBackground(new java.awt.Color(255, 255, 255));
        jrb_petitGateau.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_petitGateau.setText("Petit Gateau");
        jrb_petitGateau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_petitGateauActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel8.setText("R$ 15,00");

        jLabel9.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel9.setText("R$ 20,00");

        jLabel10.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jLabel10.setText("R$ 30,00");

        javax.swing.GroupLayout jp_sobremesasLayout = new javax.swing.GroupLayout(jp_sobremesas);
        jp_sobremesas.setLayout(jp_sobremesasLayout);
        jp_sobremesasLayout.setHorizontalGroup(
            jp_sobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sobremesasLayout.createSequentialGroup()
                .addComponent(jrb_mousse)
                .addGap(0, 41, Short.MAX_VALUE))
            .addGroup(jp_sobremesasLayout.createSequentialGroup()
                .addGroup(jp_sobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jp_sobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jp_sobremesasLayout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jrb_tortaOreo)
                        .addComponent(jrb_petitGateau, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_sobremesasLayout.setVerticalGroup(
            jp_sobremesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_sobremesasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrb_mousse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_tortaOreo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_petitGateau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jp_sobremesas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 180, 220));

        jLabel17.setFont(new java.awt.Font("Gabriola", 3, 48)); // NOI18N
        jLabel17.setText("Piatti Dello Chef");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 280, -1));

        jp_bebidas.setBackground(new java.awt.Color(255, 255, 255));
        jp_bebidas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebidas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Gabriola", 1, 18))); // NOI18N

        jrb_agua.setBackground(new java.awt.Color(255, 255, 255));
        jrb_agua.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_agua.setText("Água (com/sem gás)");
        jrb_agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_aguaActionPerformed(evt);
            }
        });

        jrb_refrigerante.setBackground(new java.awt.Color(255, 255, 255));
        jrb_refrigerante.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_refrigerante.setText("Refrigerante");
        jrb_refrigerante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_refrigeranteActionPerformed(evt);
            }
        });

        jrb_suco.setBackground(new java.awt.Color(255, 255, 255));
        jrb_suco.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_suco.setText("Suco");
        jrb_suco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_sucoActionPerformed(evt);
            }
        });

        jrb_destilado.setBackground(new java.awt.Color(255, 255, 255));
        jrb_destilado.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_destilado.setText("Destilado (dose)");
        jrb_destilado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_destiladoActionPerformed(evt);
            }
        });

        jrb_vinho.setBackground(new java.awt.Color(255, 255, 255));
        jrb_vinho.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_vinho.setText("Vinho tinto/branco/rose");
        jrb_vinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_vinhoActionPerformed(evt);
            }
        });

        jrb_cerveja.setBackground(new java.awt.Color(255, 255, 255));
        jrb_cerveja.setFont(new java.awt.Font("Gadugi", 0, 10)); // NOI18N
        jrb_cerveja.setText("Cerveja");
        jrb_cerveja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb_cervejaActionPerformed(evt);
            }
        });

        jp_cortesia.setFont(new java.awt.Font("Gadugi", 3, 10)); // NOI18N
        jp_cortesia.setText("Cortesia da casa!");

        jp_vinho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vinhoo.png"))); // NOI18N
        jp_vinho.setText("jLabel18");

        javax.swing.GroupLayout jp_bebidasLayout = new javax.swing.GroupLayout(jp_bebidas);
        jp_bebidas.setLayout(jp_bebidasLayout);
        jp_bebidasLayout.setHorizontalGroup(
            jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_bebidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_bebidasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jp_cortesia, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jp_bebidasLayout.createSequentialGroup()
                        .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_cerveja)
                            .addComponent(jrb_refrigerante)
                            .addComponent(jrb_suco)
                            .addComponent(jrb_destilado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(jp_vinho, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jp_bebidasLayout.createSequentialGroup()
                        .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrb_agua)
                            .addComponent(jrb_vinho))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jp_bebidasLayout.setVerticalGroup(
            jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jp_bebidasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jrb_agua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_bebidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_bebidasLayout.createSequentialGroup()
                        .addComponent(jrb_suco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_refrigerante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_cerveja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jrb_destilado))
                    .addComponent(jp_vinho))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrb_vinho)
                .addGap(18, 18, 18)
                .addComponent(jp_cortesia)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jp_bebidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 440, 200, 240));

        jp_fundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fundo.png"))); // NOI18N
        jp_fundo.setText("jLabel2");
        getContentPane().add(jp_fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrb_risotoPequiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_risotoPequiActionPerformed
        if(jrb_risotoPequi.isSelected()){
            jrb_risotoAlho.setSelected(false);
            jrb_macarrao.setSelected(false);
        }
    }//GEN-LAST:event_jrb_risotoPequiActionPerformed

    private void jrb_risotoAlhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_risotoAlhoActionPerformed
        if(jrb_risotoAlho.isSelected()){
            jrb_risotoPequi.setSelected(false);
            jrb_macarrao.setSelected(false);
        }
    }//GEN-LAST:event_jrb_risotoAlhoActionPerformed

    private void jrb_macarraoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_macarraoActionPerformed
        if(jrb_macarrao.isSelected()){
            jrb_risotoAlho.setSelected(false);
            jrb_risotoPequi.setSelected(false);
        }
    }//GEN-LAST:event_jrb_macarraoActionPerformed

    private void jrb_mousseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_mousseActionPerformed
        if(jrb_mousse.isSelected()){
            jrb_tortaOreo.setSelected(false);
            jrb_petitGateau.setSelected(false);
        }
    }//GEN-LAST:event_jrb_mousseActionPerformed

    private void jrb_tortaOreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_tortaOreoActionPerformed
        if(jrb_tortaOreo.isSelected()){
            jrb_mousse.setSelected(false);
            jrb_petitGateau.setSelected(false);
        }
    }//GEN-LAST:event_jrb_tortaOreoActionPerformed

    private void jrb_petitGateauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_petitGateauActionPerformed
        if(jrb_petitGateau.isSelected()){
            jrb_tortaOreo.setSelected(false);
            jrb_mousse.setSelected(false);
        }
    }//GEN-LAST:event_jrb_petitGateauActionPerformed

    private void jrb_aguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_aguaActionPerformed
        if(jrb_agua.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_suco.setSelected(false);
            jrb_refrigerante.setSelected(false);
            jrb_destilado.setSelected(false);
            jrb_vinho.setSelected(false);
        }
    }//GEN-LAST:event_jrb_aguaActionPerformed

    private void jrb_sucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_sucoActionPerformed
        if(jrb_suco.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_agua.setSelected(false);
            jrb_refrigerante.setSelected(false);
            jrb_destilado.setSelected(false);
            jrb_vinho.setSelected(false);
        }
    }//GEN-LAST:event_jrb_sucoActionPerformed

    private void jrb_refrigeranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_refrigeranteActionPerformed
        if(jrb_refrigerante.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_suco.setSelected(false);
            jrb_agua.setSelected(false);
            jrb_destilado.setSelected(false);
            jrb_vinho.setSelected(false);
        }
    }//GEN-LAST:event_jrb_refrigeranteActionPerformed

    private void jrb_cervejaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_cervejaActionPerformed
        if(jrb_cerveja.isSelected()){
            jrb_agua.setSelected(false);
            jrb_suco.setSelected(false);
            jrb_refrigerante.setSelected(false);
            jrb_destilado.setSelected(false);
            jrb_vinho.setSelected(false);
        }
    }//GEN-LAST:event_jrb_cervejaActionPerformed

    private void jrb_destiladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_destiladoActionPerformed
        if(jrb_destilado.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_suco.setSelected(false);
            jrb_refrigerante.setSelected(false);
            jrb_agua.setSelected(false);
            jrb_vinho.setSelected(false);
        }
    }//GEN-LAST:event_jrb_destiladoActionPerformed

    private void jrb_vinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb_vinhoActionPerformed
       if(jrb_vinho.isSelected()){
            jrb_cerveja.setSelected(false);
            jrb_suco.setSelected(false);
            jrb_refrigerante.setSelected(false);
            jrb_destilado.setSelected(false);
            jrb_agua.setSelected(false);
        }
    }//GEN-LAST:event_jrb_vinhoActionPerformed

    private void btn_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_calcularActionPerformed
        double total=0;
        double prato=0;
        double acompanhamento=0;
        double sobremesa=0;
        
        if(jrb_risotoAlho.isSelected()){
            prato = prato + 25.00;
        } else if (jrb_risotoPequi.isSelected()){
            prato = prato + 35.00;
        } else if (jrb_macarrao.isSelected()){
            prato = prato + 20.00;
        }
        
        if(jrb_petitGateau.isSelected()){
            sobremesa = sobremesa + 30.00;
        } else if (jrb_mousse.isSelected()){
            sobremesa = sobremesa + 15.00;
        } else if (jrb_tortaOreo.isSelected()){
            sobremesa = sobremesa + 20.00;
        }
        
        if(jcb_legumesGrelhados.isSelected()){
            acompanhamento = acompanhamento + 10.00;
        } 
        if(jcb_pimenta.isSelected()){
            acompanhamento = acompanhamento + 5.00;
        }
        if(jcb_salada.isSelected()){
            acompanhamento = acompanhamento + 8.00;
        }
        if(jcb_molho.isSelected()){
            acompanhamento = acompanhamento + 12.00;
        }
        
        total = prato + acompanhamento + sobremesa;
        
        jtf_total.setText(Double.toString(total));
        total = Double.parseDouble((jtf_total.getText()));
        
        jtf_sobremesa.setText(Double.toString(sobremesa));
        sobremesa = Double.parseDouble((jtf_sobremesa.getText()));
        
        jtf_acompanhamento.setText(Double.toString(acompanhamento));
        acompanhamento = Double.parseDouble((jtf_acompanhamento.getText()));
        
        jtf_prato.setText(Double.toString(prato));
        prato = Double.parseDouble(jtf_prato.getText());
    }//GEN-LAST:event_btn_calcularActionPerformed

    private void btn_novoPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoPedidoActionPerformed
        jrb_risotoPequi.setSelected(false);
        jrb_risotoAlho.setSelected(false);
        jrb_macarrao.setSelected(false);
        jrb_petitGateau.setSelected(false);
        jrb_tortaOreo.setSelected(false);
        jrb_mousse.setSelected(false);
        jrb_cerveja.setSelected(false);
        jrb_agua.setSelected(false);
        jrb_suco.setSelected(false);
        jrb_vinho.setSelected(false);
        jrb_refrigerante.setSelected(false);
        jrb_destilado.setSelected(false);
        jrb_agua.setSelected(false);
        jcb_salada.setSelected(false);
        jcb_molho.setSelected(false);
        jcb_legumesGrelhados.setSelected(false);
        jcb_pimenta.setSelected(false);
        jtf_total.setText(" ");
        jtf_prato.setText(" ");
        jtf_sobremesa.setText(" ");
        jtf_acompanhamento.setText(" ");
        
    }//GEN-LAST:event_btn_novoPedidoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trabalho_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trabalho_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trabalho_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trabalho_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trabalho_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calcular;
    private javax.swing.JButton btn_novoPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jcb_legumesGrelhados;
    private javax.swing.JCheckBox jcb_molho;
    private javax.swing.JCheckBox jcb_pimenta;
    private javax.swing.JCheckBox jcb_salada;
    private javax.swing.JPanel jp_acompanhamento;
    private javax.swing.JPanel jp_bebidas;
    private javax.swing.JLabel jp_cortesia;
    private javax.swing.JLabel jp_fundo;
    private javax.swing.JLabel jp_pequi;
    private javax.swing.JPanel jp_pratos;
    private javax.swing.JPanel jp_sobremesas;
    private javax.swing.JLabel jp_vinho;
    private javax.swing.JRadioButton jrb_agua;
    private javax.swing.JRadioButton jrb_cerveja;
    private javax.swing.JRadioButton jrb_destilado;
    private javax.swing.JRadioButton jrb_macarrao;
    private javax.swing.JRadioButton jrb_mousse;
    private javax.swing.JRadioButton jrb_petitGateau;
    private javax.swing.JRadioButton jrb_refrigerante;
    private javax.swing.JRadioButton jrb_risotoAlho;
    private javax.swing.JRadioButton jrb_risotoPequi;
    private javax.swing.JRadioButton jrb_suco;
    private javax.swing.JRadioButton jrb_tortaOreo;
    private javax.swing.JRadioButton jrb_vinho;
    private javax.swing.JTextField jtf_acompanhamento;
    private javax.swing.JTextField jtf_prato;
    private javax.swing.JTextField jtf_sobremesa;
    private javax.swing.JTextField jtf_total;
    // End of variables declaration//GEN-END:variables
}
